### ISSUE TITLE
Listen to TCP/IP socket?

### ISSUE THREAD

**Issue by fredleeflang** [tanmaykm/FastCGI.jl#4]
Hi,

I'm not familiar with Julia yet so the answer may be quite obvious, but is it possible to use a TCP/IP socket instead of a Unix socket? If so, how?

-Fred

**Comment by tanmaykm** [comment]
Yes, it is possible to instantiate the server to listen on a TCP port. E.g. `server = FCGIServer(host, port)`.

You may find a relevant example [here](https://github.com/tanmaykm/FastCGI.jl/blob/a03f93f78ef81ae75c4b9f39c3f2c2908b511a25/test/runtests.jl#L123)
